#!/bin/sh
# See tensorflow/lite/examples/minimal/README.md
# This test builds a simple TensorFlow Lite application.

set -e

cd debian/tests/

cmake .
cmake --build . -j

# FIXME we need a tflite model in the Debian archive for a real test
./minimal | true

# wget https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
# tar -zxvf mobilenet_v1_1.0_224.tgz ./mobilenet_v1_1.0_224.tflite
# ./minimal ./mobilenet_v1_1.0_224.tflite
